server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com

logging:
  level:
    org:
      springframework:
        web:
          socket: DEBUG
        messaging: TRACE




