server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com
  data:
    mongodb:
      uri: mongodb://localhost:27017/message-app-mongodb
      database: message-app


#logging:
#  level:
#    org:
#      springframework:
#        web:
#          socket: DEBUG
#        messaging: TRACE




